# ===========================
# 1. BACKEND DEPLOYMENT
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-backend
  template:
    metadata:
      labels:
        app: flight-backend
    spec:
      containers:
      - name: backend
        image: flight-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        # === TAMBAHKAN BAGIAN INI ===
        resources:
          requests:
            cpu: "100m"  # Meminta jatah 0.1 CPU (100 millicores)
            memory: "128Mi"
          limits:
            cpu: "500m"  # Maksimal boleh pakai 0.5 CPU
            memory: "512Mi"
---
# ===========================
# 2. BACKEND SERVICE (ClusterIP)
# ===========================
apiVersion: v1
kind: Service
metadata:
  name: backend-service # <--- Ini akan jadi DNS name untuk backend
spec:
  selector:
    app: flight-backend
  ports:
    - protocol: TCP
      port: 8000        # Port yang dibuka di dalam cluster
      targetPort: 8000  # Port container
  type: ClusterIP       # Hanya bisa diakses dari dalam cluster

---
# ===========================
# 3. FRONTEND DEPLOYMENT
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-frontend
  template:
    metadata:
      labels:
        app: flight-frontend
    spec:
      containers:
      - name: frontend
        image: flight-frontend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        env:
        # Menghubungkan variabel API_URL di Python ke Service Kubernetes
        - name: API_URL
          value: "http://backend-service:8000/predict"
---
# ===========================
# 4. FRONTEND SERVICE (LoadBalancer)
# ===========================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: flight-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer # Agar bisa diakses dari browser host